# Generated by Django 5.0 on 2023-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('item_list', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
